# NATS server URL
nats:
  url: "nats://localhost:4222"

discord:
  token: "YOUR_BOT_TOKEN"
  opt_in_message_id: "YOUR_OPT_IN_MESSAGE_ID" # ID of the message with the reaction
  opt_in_channel_id: "YOUR_OPT_IN_CHANNEL_ID" # ID of the channel with the message
  registered_role_id: "YOUR_REGISTERED_ROLE_ID" # ID of the "Registered" role
  guild_id: "YOUR_GUILD_ID" # ID of your server
  app_id: "YOUR_APP_ID"

Loki:
  url: "http://localhost:3100"
  enabled: true

Tempo:
  url: "http://localhost:3200"
  username: "admin"
  password: "admin"
