// Code generated by MockGen. DO NOT EDIT.
// Source: ./app/round/discord/delete_round/delete_round.go
//
// Generated by this command:
//
//	mockgen -source=./app/round/discord/delete_round/delete_round.go -destination=./app/round/mocks/mock_delete_round_manager.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	deleteround "github.com/Black-And-White-Club/discord-frolf-bot/app/round/discord/delete_round"
	discordgo "github.com/bwmarrin/discordgo"
	gomock "go.uber.org/mock/gomock"
)

// MockDeleteRoundManager is a mock of DeleteRoundManager interface.
type MockDeleteRoundManager struct {
	ctrl     *gomock.Controller
	recorder *MockDeleteRoundManagerMockRecorder
	isgomock struct{}
}

// MockDeleteRoundManagerMockRecorder is the mock recorder for MockDeleteRoundManager.
type MockDeleteRoundManagerMockRecorder struct {
	mock *MockDeleteRoundManager
}

// NewMockDeleteRoundManager creates a new mock instance.
func NewMockDeleteRoundManager(ctrl *gomock.Controller) *MockDeleteRoundManager {
	mock := &MockDeleteRoundManager{ctrl: ctrl}
	mock.recorder = &MockDeleteRoundManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDeleteRoundManager) EXPECT() *MockDeleteRoundManagerMockRecorder {
	return m.recorder
}

// DeleteRoundEventEmbed mocks base method.
func (m *MockDeleteRoundManager) DeleteRoundEventEmbed(ctx context.Context, discordMessageID, channelID string) (deleteround.DeleteRoundOperationResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteRoundEventEmbed", ctx, discordMessageID, channelID)
	ret0, _ := ret[0].(deleteround.DeleteRoundOperationResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteRoundEventEmbed indicates an expected call of DeleteRoundEventEmbed.
func (mr *MockDeleteRoundManagerMockRecorder) DeleteRoundEventEmbed(ctx, discordMessageID, channelID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteRoundEventEmbed", reflect.TypeOf((*MockDeleteRoundManager)(nil).DeleteRoundEventEmbed), ctx, discordMessageID, channelID)
}

// HandleDeleteRoundButton mocks base method.
func (m *MockDeleteRoundManager) HandleDeleteRoundButton(ctx context.Context, i *discordgo.InteractionCreate) (deleteround.DeleteRoundOperationResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleDeleteRoundButton", ctx, i)
	ret0, _ := ret[0].(deleteround.DeleteRoundOperationResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HandleDeleteRoundButton indicates an expected call of HandleDeleteRoundButton.
func (mr *MockDeleteRoundManagerMockRecorder) HandleDeleteRoundButton(ctx, i any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleDeleteRoundButton", reflect.TypeOf((*MockDeleteRoundManager)(nil).HandleDeleteRoundButton), ctx, i)
}
