// Code generated by MockGen. DO NOT EDIT.
// Source: ./app/user/watermill/handlers/handlers.go
//
// Generated by this command:
//
//	mockgen -source=./app/user/watermill/handlers/handlers.go -destination=./app/user/mocks/mock_handlers.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks
