// Code generated by MockGen. DO NOT EDIT.
// Source: ./discord/gateway.go
//
// Generated by this command:
//
//	mockgen -source=./discord/gateway.go -destination=./mocks/mock_gateway.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	discordgo "github.com/bwmarrin/discordgo"
	gomock "go.uber.org/mock/gomock"
)

// MockGatewayEventHandler is a mock of GatewayEventHandler interface.
type MockGatewayEventHandler struct {
	ctrl     *gomock.Controller
	recorder *MockGatewayEventHandlerMockRecorder
	isgomock struct{}
}

// MockGatewayEventHandlerMockRecorder is the mock recorder for MockGatewayEventHandler.
type MockGatewayEventHandlerMockRecorder struct {
	mock *MockGatewayEventHandler
}

// NewMockGatewayEventHandler creates a new mock instance.
func NewMockGatewayEventHandler(ctrl *gomock.Controller) *MockGatewayEventHandler {
	mock := &MockGatewayEventHandler{ctrl: ctrl}
	mock.recorder = &MockGatewayEventHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGatewayEventHandler) EXPECT() *MockGatewayEventHandlerMockRecorder {
	return m.recorder
}

// HandleRoleButtonPress mocks base method.
func (m *MockGatewayEventHandler) HandleRoleButtonPress(ctx context.Context, i *discordgo.InteractionCreate) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "HandleRoleButtonPress", ctx, i)
}

// HandleRoleButtonPress indicates an expected call of HandleRoleButtonPress.
func (mr *MockGatewayEventHandlerMockRecorder) HandleRoleButtonPress(ctx, i any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleRoleButtonPress", reflect.TypeOf((*MockGatewayEventHandler)(nil).HandleRoleButtonPress), ctx, i)
}

// HandleRoleCancelButton mocks base method.
func (m *MockGatewayEventHandler) HandleRoleCancelButton(ctx context.Context, i *discordgo.InteractionCreate) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "HandleRoleCancelButton", ctx, i)
}

// HandleRoleCancelButton indicates an expected call of HandleRoleCancelButton.
func (mr *MockGatewayEventHandlerMockRecorder) HandleRoleCancelButton(ctx, i any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleRoleCancelButton", reflect.TypeOf((*MockGatewayEventHandler)(nil).HandleRoleCancelButton), ctx, i)
}

// HandleRoleRequestCommand mocks base method.
func (m *MockGatewayEventHandler) HandleRoleRequestCommand(ctx context.Context, i *discordgo.InteractionCreate) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "HandleRoleRequestCommand", ctx, i)
}

// HandleRoleRequestCommand indicates an expected call of HandleRoleRequestCommand.
func (mr *MockGatewayEventHandlerMockRecorder) HandleRoleRequestCommand(ctx, i any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleRoleRequestCommand", reflect.TypeOf((*MockGatewayEventHandler)(nil).HandleRoleRequestCommand), ctx, i)
}

// HandleSignupButtonPress mocks base method.
func (m *MockGatewayEventHandler) HandleSignupButtonPress(ctx context.Context, i *discordgo.InteractionCreate) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "HandleSignupButtonPress", ctx, i)
}

// HandleSignupButtonPress indicates an expected call of HandleSignupButtonPress.
func (mr *MockGatewayEventHandlerMockRecorder) HandleSignupButtonPress(ctx, i any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleSignupButtonPress", reflect.TypeOf((*MockGatewayEventHandler)(nil).HandleSignupButtonPress), ctx, i)
}

// HandleSignupModalSubmit mocks base method.
func (m *MockGatewayEventHandler) HandleSignupModalSubmit(ctx context.Context, i *discordgo.InteractionCreate) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "HandleSignupModalSubmit", ctx, i)
}

// HandleSignupModalSubmit indicates an expected call of HandleSignupModalSubmit.
func (mr *MockGatewayEventHandlerMockRecorder) HandleSignupModalSubmit(ctx, i any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleSignupModalSubmit", reflect.TypeOf((*MockGatewayEventHandler)(nil).HandleSignupModalSubmit), ctx, i)
}

// HandleSignupReactionAdd mocks base method.
func (m *MockGatewayEventHandler) HandleSignupReactionAdd(ctx context.Context, r *discordgo.MessageReactionAdd) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "HandleSignupReactionAdd", ctx, r)
}

// HandleSignupReactionAdd indicates an expected call of HandleSignupReactionAdd.
func (mr *MockGatewayEventHandlerMockRecorder) HandleSignupReactionAdd(ctx, r any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleSignupReactionAdd", reflect.TypeOf((*MockGatewayEventHandler)(nil).HandleSignupReactionAdd), ctx, r)
}

// InteractionCreate mocks base method.
func (m *MockGatewayEventHandler) InteractionCreate(s *discordgo.Session, i *discordgo.InteractionCreate) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "InteractionCreate", s, i)
}

// InteractionCreate indicates an expected call of InteractionCreate.
func (mr *MockGatewayEventHandlerMockRecorder) InteractionCreate(s, i any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InteractionCreate", reflect.TypeOf((*MockGatewayEventHandler)(nil).InteractionCreate), s, i)
}

// MessageReactionAdd mocks base method.
func (m *MockGatewayEventHandler) MessageReactionAdd(s *discordgo.Session, r *discordgo.MessageReactionAdd) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "MessageReactionAdd", s, r)
}

// MessageReactionAdd indicates an expected call of MessageReactionAdd.
func (mr *MockGatewayEventHandlerMockRecorder) MessageReactionAdd(s, r any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MessageReactionAdd", reflect.TypeOf((*MockGatewayEventHandler)(nil).MessageReactionAdd), s, r)
}
