// Code generated by MockGen. DO NOT EDIT.
// Source: ./helpers/helpers.go
//
// Generated by this command:
//
//	mockgen -source=./helpers/helpers.go -destination=./mocks/mock_helpers.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks
