// Code generated by MockGen. DO NOT EDIT.
// Source: ./app/guild/watermill/handlers/interface.go
//
// Generated by this command:
//
//	mockgen -source=./app/guild/watermill/handlers/interface.go -destination=./app/guild/mocks/mock_guild_handlers.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	guildevents "github.com/Black-And-White-Club/frolf-bot-shared/events/guild"
	handlerwrapper "github.com/Black-And-White-Club/frolf-bot-shared/utils/handlerwrapper"
	gomock "go.uber.org/mock/gomock"
)

// MockHandlers is a mock of Handlers interface.
type MockHandlers struct {
	ctrl     *gomock.Controller
	recorder *MockHandlersMockRecorder
	isgomock struct{}
}

// MockHandlersMockRecorder is the mock recorder for MockHandlers.
type MockHandlersMockRecorder struct {
	mock *MockHandlers
}

// NewMockHandlers creates a new mock instance.
func NewMockHandlers(ctrl *gomock.Controller) *MockHandlers {
	mock := &MockHandlers{ctrl: ctrl}
	mock.recorder = &MockHandlersMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHandlers) EXPECT() *MockHandlersMockRecorder {
	return m.recorder
}

// HandleGuildConfigCreated mocks base method.
func (m *MockHandlers) HandleGuildConfigCreated(ctx context.Context, payload *guildevents.GuildConfigCreatedPayloadV1) ([]handlerwrapper.Result, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleGuildConfigCreated", ctx, payload)
	ret0, _ := ret[0].([]handlerwrapper.Result)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HandleGuildConfigCreated indicates an expected call of HandleGuildConfigCreated.
func (mr *MockHandlersMockRecorder) HandleGuildConfigCreated(ctx, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleGuildConfigCreated", reflect.TypeOf((*MockHandlers)(nil).HandleGuildConfigCreated), ctx, payload)
}

// HandleGuildConfigCreationFailed mocks base method.
func (m *MockHandlers) HandleGuildConfigCreationFailed(ctx context.Context, payload *guildevents.GuildConfigCreationFailedPayloadV1) ([]handlerwrapper.Result, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleGuildConfigCreationFailed", ctx, payload)
	ret0, _ := ret[0].([]handlerwrapper.Result)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HandleGuildConfigCreationFailed indicates an expected call of HandleGuildConfigCreationFailed.
func (mr *MockHandlersMockRecorder) HandleGuildConfigCreationFailed(ctx, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleGuildConfigCreationFailed", reflect.TypeOf((*MockHandlers)(nil).HandleGuildConfigCreationFailed), ctx, payload)
}

// HandleGuildConfigDeleted mocks base method.
func (m *MockHandlers) HandleGuildConfigDeleted(ctx context.Context, payload *guildevents.GuildConfigDeletedPayloadV1) ([]handlerwrapper.Result, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleGuildConfigDeleted", ctx, payload)
	ret0, _ := ret[0].([]handlerwrapper.Result)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HandleGuildConfigDeleted indicates an expected call of HandleGuildConfigDeleted.
func (mr *MockHandlersMockRecorder) HandleGuildConfigDeleted(ctx, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleGuildConfigDeleted", reflect.TypeOf((*MockHandlers)(nil).HandleGuildConfigDeleted), ctx, payload)
}

// HandleGuildConfigDeletionFailed mocks base method.
func (m *MockHandlers) HandleGuildConfigDeletionFailed(ctx context.Context, payload *guildevents.GuildConfigDeletionFailedPayloadV1) ([]handlerwrapper.Result, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleGuildConfigDeletionFailed", ctx, payload)
	ret0, _ := ret[0].([]handlerwrapper.Result)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HandleGuildConfigDeletionFailed indicates an expected call of HandleGuildConfigDeletionFailed.
func (mr *MockHandlersMockRecorder) HandleGuildConfigDeletionFailed(ctx, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleGuildConfigDeletionFailed", reflect.TypeOf((*MockHandlers)(nil).HandleGuildConfigDeletionFailed), ctx, payload)
}

// HandleGuildConfigRetrievalFailed mocks base method.
func (m *MockHandlers) HandleGuildConfigRetrievalFailed(ctx context.Context, payload *guildevents.GuildConfigRetrievalFailedPayloadV1) ([]handlerwrapper.Result, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleGuildConfigRetrievalFailed", ctx, payload)
	ret0, _ := ret[0].([]handlerwrapper.Result)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HandleGuildConfigRetrievalFailed indicates an expected call of HandleGuildConfigRetrievalFailed.
func (mr *MockHandlersMockRecorder) HandleGuildConfigRetrievalFailed(ctx, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleGuildConfigRetrievalFailed", reflect.TypeOf((*MockHandlers)(nil).HandleGuildConfigRetrievalFailed), ctx, payload)
}

// HandleGuildConfigRetrieved mocks base method.
func (m *MockHandlers) HandleGuildConfigRetrieved(ctx context.Context, payload *guildevents.GuildConfigRetrievedPayloadV1) ([]handlerwrapper.Result, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleGuildConfigRetrieved", ctx, payload)
	ret0, _ := ret[0].([]handlerwrapper.Result)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HandleGuildConfigRetrieved indicates an expected call of HandleGuildConfigRetrieved.
func (mr *MockHandlersMockRecorder) HandleGuildConfigRetrieved(ctx, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleGuildConfigRetrieved", reflect.TypeOf((*MockHandlers)(nil).HandleGuildConfigRetrieved), ctx, payload)
}

// HandleGuildConfigUpdateFailed mocks base method.
func (m *MockHandlers) HandleGuildConfigUpdateFailed(ctx context.Context, payload *guildevents.GuildConfigUpdateFailedPayloadV1) ([]handlerwrapper.Result, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleGuildConfigUpdateFailed", ctx, payload)
	ret0, _ := ret[0].([]handlerwrapper.Result)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HandleGuildConfigUpdateFailed indicates an expected call of HandleGuildConfigUpdateFailed.
func (mr *MockHandlersMockRecorder) HandleGuildConfigUpdateFailed(ctx, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleGuildConfigUpdateFailed", reflect.TypeOf((*MockHandlers)(nil).HandleGuildConfigUpdateFailed), ctx, payload)
}

// HandleGuildConfigUpdated mocks base method.
func (m *MockHandlers) HandleGuildConfigUpdated(ctx context.Context, payload *guildevents.GuildConfigUpdatedPayloadV1) ([]handlerwrapper.Result, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleGuildConfigUpdated", ctx, payload)
	ret0, _ := ret[0].([]handlerwrapper.Result)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HandleGuildConfigUpdated indicates an expected call of HandleGuildConfigUpdated.
func (mr *MockHandlersMockRecorder) HandleGuildConfigUpdated(ctx, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleGuildConfigUpdated", reflect.TypeOf((*MockHandlers)(nil).HandleGuildConfigUpdated), ctx, payload)
}
