// Code generated by MockGen. DO NOT EDIT.
// Source: ./app/guild/discord/reset/reset.go
//
// Generated by this command:
//
//	mockgen -source=./app/guild/discord/reset/reset.go -destination=./app/guild/mocks/mock_reset_manager.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	guild "github.com/Black-And-White-Club/frolf-bot-shared/types/guild"
	discordgo "github.com/bwmarrin/discordgo"
	gomock "go.uber.org/mock/gomock"
)

// MockResetManager is a mock of ResetManager interface.
type MockResetManager struct {
	ctrl     *gomock.Controller
	recorder *MockResetManagerMockRecorder
	isgomock struct{}
}

// MockResetManagerMockRecorder is the mock recorder for MockResetManager.
type MockResetManagerMockRecorder struct {
	mock *MockResetManager
}

// NewMockResetManager creates a new mock instance.
func NewMockResetManager(ctrl *gomock.Controller) *MockResetManager {
	mock := &MockResetManager{ctrl: ctrl}
	mock.recorder = &MockResetManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockResetManager) EXPECT() *MockResetManagerMockRecorder {
	return m.recorder
}

// DeleteResources mocks base method.
func (m *MockResetManager) DeleteResources(ctx context.Context, guildID string, state guild.ResourceState) (map[string]guild.DeletionResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteResources", ctx, guildID, state)
	ret0, _ := ret[0].(map[string]guild.DeletionResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteResources indicates an expected call of DeleteResources.
func (mr *MockResetManagerMockRecorder) DeleteResources(ctx, guildID, state any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteResources", reflect.TypeOf((*MockResetManager)(nil).DeleteResources), ctx, guildID, state)
}

// HandleResetCancelButton mocks base method.
func (m *MockResetManager) HandleResetCancelButton(ctx context.Context, i *discordgo.InteractionCreate) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleResetCancelButton", ctx, i)
	ret0, _ := ret[0].(error)
	return ret0
}

// HandleResetCancelButton indicates an expected call of HandleResetCancelButton.
func (mr *MockResetManagerMockRecorder) HandleResetCancelButton(ctx, i any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleResetCancelButton", reflect.TypeOf((*MockResetManager)(nil).HandleResetCancelButton), ctx, i)
}

// HandleResetCommand mocks base method.
func (m *MockResetManager) HandleResetCommand(ctx context.Context, i *discordgo.InteractionCreate) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleResetCommand", ctx, i)
	ret0, _ := ret[0].(error)
	return ret0
}

// HandleResetCommand indicates an expected call of HandleResetCommand.
func (mr *MockResetManagerMockRecorder) HandleResetCommand(ctx, i any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleResetCommand", reflect.TypeOf((*MockResetManager)(nil).HandleResetCommand), ctx, i)
}

// HandleResetConfirmButton mocks base method.
func (m *MockResetManager) HandleResetConfirmButton(ctx context.Context, i *discordgo.InteractionCreate) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleResetConfirmButton", ctx, i)
	ret0, _ := ret[0].(error)
	return ret0
}

// HandleResetConfirmButton indicates an expected call of HandleResetConfirmButton.
func (mr *MockResetManagerMockRecorder) HandleResetConfirmButton(ctx, i any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleResetConfirmButton", reflect.TypeOf((*MockResetManager)(nil).HandleResetConfirmButton), ctx, i)
}
