// Code generated by MockGen. DO NOT EDIT.
// Source: ./app/leaderboard/watermill/handlers/handlers.go
//
// Generated by this command:
//
//	mockgen -source=./app/leaderboard/watermill/handlers/handlers.go -destination=./app/leaderboard/mocks/mock_handlers.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	handlerwrapper "github.com/Black-And-White-Club/frolf-bot-shared/utils/handlerwrapper"
	gomock "go.uber.org/mock/gomock"
)

// MockHandlers is a mock of Handlers interface.
type MockHandlers struct {
	ctrl     *gomock.Controller
	recorder *MockHandlersMockRecorder
	isgomock struct{}
}

// MockHandlersMockRecorder is the mock recorder for MockHandlers.
type MockHandlersMockRecorder struct {
	mock *MockHandlers
}

// NewMockHandlers creates a new mock instance.
func NewMockHandlers(ctrl *gomock.Controller) *MockHandlers {
	mock := &MockHandlers{ctrl: ctrl}
	mock.recorder = &MockHandlersMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHandlers) EXPECT() *MockHandlersMockRecorder {
	return m.recorder
}

// HandleBatchTagAssigned mocks base method.
func (m *MockHandlers) HandleBatchTagAssigned(ctx context.Context, payload any) ([]handlerwrapper.Result, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleBatchTagAssigned", ctx, payload)
	ret0, _ := ret[0].([]handlerwrapper.Result)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HandleBatchTagAssigned indicates an expected call of HandleBatchTagAssigned.
func (mr *MockHandlersMockRecorder) HandleBatchTagAssigned(ctx, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleBatchTagAssigned", reflect.TypeOf((*MockHandlers)(nil).HandleBatchTagAssigned), ctx, payload)
}

// HandleGetTagByDiscordID mocks base method.
func (m *MockHandlers) HandleGetTagByDiscordID(ctx context.Context, payload any) ([]handlerwrapper.Result, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleGetTagByDiscordID", ctx, payload)
	ret0, _ := ret[0].([]handlerwrapper.Result)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HandleGetTagByDiscordID indicates an expected call of HandleGetTagByDiscordID.
func (mr *MockHandlersMockRecorder) HandleGetTagByDiscordID(ctx, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleGetTagByDiscordID", reflect.TypeOf((*MockHandlers)(nil).HandleGetTagByDiscordID), ctx, payload)
}

// HandleGetTagByDiscordIDFailed mocks base method.
func (m *MockHandlers) HandleGetTagByDiscordIDFailed(ctx context.Context, payload any) ([]handlerwrapper.Result, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleGetTagByDiscordIDFailed", ctx, payload)
	ret0, _ := ret[0].([]handlerwrapper.Result)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HandleGetTagByDiscordIDFailed indicates an expected call of HandleGetTagByDiscordIDFailed.
func (mr *MockHandlersMockRecorder) HandleGetTagByDiscordIDFailed(ctx, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleGetTagByDiscordIDFailed", reflect.TypeOf((*MockHandlers)(nil).HandleGetTagByDiscordIDFailed), ctx, payload)
}

// HandleGetTagByDiscordIDResponse mocks base method.
func (m *MockHandlers) HandleGetTagByDiscordIDResponse(ctx context.Context, payload any) ([]handlerwrapper.Result, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleGetTagByDiscordIDResponse", ctx, payload)
	ret0, _ := ret[0].([]handlerwrapper.Result)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HandleGetTagByDiscordIDResponse indicates an expected call of HandleGetTagByDiscordIDResponse.
func (mr *MockHandlersMockRecorder) HandleGetTagByDiscordIDResponse(ctx, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleGetTagByDiscordIDResponse", reflect.TypeOf((*MockHandlers)(nil).HandleGetTagByDiscordIDResponse), ctx, payload)
}

// HandleLeaderboardResponse mocks base method.
func (m *MockHandlers) HandleLeaderboardResponse(ctx context.Context, payload any) ([]handlerwrapper.Result, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleLeaderboardResponse", ctx, payload)
	ret0, _ := ret[0].([]handlerwrapper.Result)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HandleLeaderboardResponse indicates an expected call of HandleLeaderboardResponse.
func (mr *MockHandlersMockRecorder) HandleLeaderboardResponse(ctx, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleLeaderboardResponse", reflect.TypeOf((*MockHandlers)(nil).HandleLeaderboardResponse), ctx, payload)
}

// HandleLeaderboardRetrievalFailed mocks base method.
func (m *MockHandlers) HandleLeaderboardRetrievalFailed(ctx context.Context, payload any) ([]handlerwrapper.Result, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleLeaderboardRetrievalFailed", ctx, payload)
	ret0, _ := ret[0].([]handlerwrapper.Result)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HandleLeaderboardRetrievalFailed indicates an expected call of HandleLeaderboardRetrievalFailed.
func (mr *MockHandlersMockRecorder) HandleLeaderboardRetrievalFailed(ctx, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleLeaderboardRetrievalFailed", reflect.TypeOf((*MockHandlers)(nil).HandleLeaderboardRetrievalFailed), ctx, payload)
}

// HandleLeaderboardRetrieveRequest mocks base method.
func (m *MockHandlers) HandleLeaderboardRetrieveRequest(ctx context.Context, payload any) ([]handlerwrapper.Result, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleLeaderboardRetrieveRequest", ctx, payload)
	ret0, _ := ret[0].([]handlerwrapper.Result)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HandleLeaderboardRetrieveRequest indicates an expected call of HandleLeaderboardRetrieveRequest.
func (mr *MockHandlersMockRecorder) HandleLeaderboardRetrieveRequest(ctx, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleLeaderboardRetrieveRequest", reflect.TypeOf((*MockHandlers)(nil).HandleLeaderboardRetrieveRequest), ctx, payload)
}

// HandleLeaderboardUpdateFailed mocks base method.
func (m *MockHandlers) HandleLeaderboardUpdateFailed(ctx context.Context, payload any) ([]handlerwrapper.Result, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleLeaderboardUpdateFailed", ctx, payload)
	ret0, _ := ret[0].([]handlerwrapper.Result)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HandleLeaderboardUpdateFailed indicates an expected call of HandleLeaderboardUpdateFailed.
func (mr *MockHandlersMockRecorder) HandleLeaderboardUpdateFailed(ctx, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleLeaderboardUpdateFailed", reflect.TypeOf((*MockHandlers)(nil).HandleLeaderboardUpdateFailed), ctx, payload)
}

// HandleLeaderboardUpdatedNotification mocks base method.
func (m *MockHandlers) HandleLeaderboardUpdatedNotification(ctx context.Context, payload any) ([]handlerwrapper.Result, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleLeaderboardUpdatedNotification", ctx, payload)
	ret0, _ := ret[0].([]handlerwrapper.Result)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HandleLeaderboardUpdatedNotification indicates an expected call of HandleLeaderboardUpdatedNotification.
func (mr *MockHandlersMockRecorder) HandleLeaderboardUpdatedNotification(ctx, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleLeaderboardUpdatedNotification", reflect.TypeOf((*MockHandlers)(nil).HandleLeaderboardUpdatedNotification), ctx, payload)
}

// HandleTagAssignFailedResponse mocks base method.
func (m *MockHandlers) HandleTagAssignFailedResponse(ctx context.Context, payload any) ([]handlerwrapper.Result, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleTagAssignFailedResponse", ctx, payload)
	ret0, _ := ret[0].([]handlerwrapper.Result)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HandleTagAssignFailedResponse indicates an expected call of HandleTagAssignFailedResponse.
func (mr *MockHandlersMockRecorder) HandleTagAssignFailedResponse(ctx, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleTagAssignFailedResponse", reflect.TypeOf((*MockHandlers)(nil).HandleTagAssignFailedResponse), ctx, payload)
}

// HandleTagAssignRequest mocks base method.
func (m *MockHandlers) HandleTagAssignRequest(ctx context.Context, payload any) ([]handlerwrapper.Result, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleTagAssignRequest", ctx, payload)
	ret0, _ := ret[0].([]handlerwrapper.Result)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HandleTagAssignRequest indicates an expected call of HandleTagAssignRequest.
func (mr *MockHandlersMockRecorder) HandleTagAssignRequest(ctx, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleTagAssignRequest", reflect.TypeOf((*MockHandlers)(nil).HandleTagAssignRequest), ctx, payload)
}

// HandleTagAssignedResponse mocks base method.
func (m *MockHandlers) HandleTagAssignedResponse(ctx context.Context, payload any) ([]handlerwrapper.Result, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleTagAssignedResponse", ctx, payload)
	ret0, _ := ret[0].([]handlerwrapper.Result)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HandleTagAssignedResponse indicates an expected call of HandleTagAssignedResponse.
func (mr *MockHandlersMockRecorder) HandleTagAssignedResponse(ctx, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleTagAssignedResponse", reflect.TypeOf((*MockHandlers)(nil).HandleTagAssignedResponse), ctx, payload)
}

// HandleTagSwapFailedResponse mocks base method.
func (m *MockHandlers) HandleTagSwapFailedResponse(ctx context.Context, payload any) ([]handlerwrapper.Result, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleTagSwapFailedResponse", ctx, payload)
	ret0, _ := ret[0].([]handlerwrapper.Result)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HandleTagSwapFailedResponse indicates an expected call of HandleTagSwapFailedResponse.
func (mr *MockHandlersMockRecorder) HandleTagSwapFailedResponse(ctx, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleTagSwapFailedResponse", reflect.TypeOf((*MockHandlers)(nil).HandleTagSwapFailedResponse), ctx, payload)
}

// HandleTagSwapRequest mocks base method.
func (m *MockHandlers) HandleTagSwapRequest(ctx context.Context, payload any) ([]handlerwrapper.Result, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleTagSwapRequest", ctx, payload)
	ret0, _ := ret[0].([]handlerwrapper.Result)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HandleTagSwapRequest indicates an expected call of HandleTagSwapRequest.
func (mr *MockHandlersMockRecorder) HandleTagSwapRequest(ctx, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleTagSwapRequest", reflect.TypeOf((*MockHandlers)(nil).HandleTagSwapRequest), ctx, payload)
}

// HandleTagSwappedResponse mocks base method.
func (m *MockHandlers) HandleTagSwappedResponse(ctx context.Context, payload any) ([]handlerwrapper.Result, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleTagSwappedResponse", ctx, payload)
	ret0, _ := ret[0].([]handlerwrapper.Result)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HandleTagSwappedResponse indicates an expected call of HandleTagSwappedResponse.
func (mr *MockHandlersMockRecorder) HandleTagSwappedResponse(ctx, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleTagSwappedResponse", reflect.TypeOf((*MockHandlers)(nil).HandleTagSwappedResponse), ctx, payload)
}
