// Code generated by MockGen. DO NOT EDIT.
// Source: ./app/score/watermill/handlers/handlers.go
//
// Generated by this command:
//
//	mockgen -source=./app/score/watermill/handlers/handlers.go -destination=./app/score/mocks/handlers.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	score "github.com/Black-And-White-Club/frolf-bot-shared/events/discord/score"
	shared "github.com/Black-And-White-Club/frolf-bot-shared/events/shared"
	handlerwrapper "github.com/Black-And-White-Club/frolf-bot-shared/utils/handlerwrapper"
	gomock "go.uber.org/mock/gomock"
)

// MockHandlers is a mock of Handlers interface.
type MockHandlers struct {
	ctrl     *gomock.Controller
	recorder *MockHandlersMockRecorder
	isgomock struct{}
}

// MockHandlersMockRecorder is the mock recorder for MockHandlers.
type MockHandlersMockRecorder struct {
	mock *MockHandlers
}

// NewMockHandlers creates a new mock instance.
func NewMockHandlers(ctrl *gomock.Controller) *MockHandlers {
	mock := &MockHandlers{ctrl: ctrl}
	mock.recorder = &MockHandlersMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHandlers) EXPECT() *MockHandlersMockRecorder {
	return m.recorder
}

// HandleProcessRoundScoresFailedTyped mocks base method.
func (m *MockHandlers) HandleProcessRoundScoresFailedTyped(ctx context.Context, payload *shared.ProcessRoundScoresFailedPayloadV1) ([]handlerwrapper.Result, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleProcessRoundScoresFailedTyped", ctx, payload)
	ret0, _ := ret[0].([]handlerwrapper.Result)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HandleProcessRoundScoresFailedTyped indicates an expected call of HandleProcessRoundScoresFailedTyped.
func (mr *MockHandlersMockRecorder) HandleProcessRoundScoresFailedTyped(ctx, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleProcessRoundScoresFailedTyped", reflect.TypeOf((*MockHandlers)(nil).HandleProcessRoundScoresFailedTyped), ctx, payload)
}

// HandleScoreUpdateFailureTyped mocks base method.
func (m *MockHandlers) HandleScoreUpdateFailureTyped(ctx context.Context, payload *shared.ScoreUpdateFailedPayloadV1) ([]handlerwrapper.Result, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleScoreUpdateFailureTyped", ctx, payload)
	ret0, _ := ret[0].([]handlerwrapper.Result)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HandleScoreUpdateFailureTyped indicates an expected call of HandleScoreUpdateFailureTyped.
func (mr *MockHandlersMockRecorder) HandleScoreUpdateFailureTyped(ctx, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleScoreUpdateFailureTyped", reflect.TypeOf((*MockHandlers)(nil).HandleScoreUpdateFailureTyped), ctx, payload)
}

// HandleScoreUpdateRequestTyped mocks base method.
func (m *MockHandlers) HandleScoreUpdateRequestTyped(ctx context.Context, payload *score.ScoreUpdateRequestDiscordPayloadV1) ([]handlerwrapper.Result, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleScoreUpdateRequestTyped", ctx, payload)
	ret0, _ := ret[0].([]handlerwrapper.Result)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HandleScoreUpdateRequestTyped indicates an expected call of HandleScoreUpdateRequestTyped.
func (mr *MockHandlersMockRecorder) HandleScoreUpdateRequestTyped(ctx, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleScoreUpdateRequestTyped", reflect.TypeOf((*MockHandlers)(nil).HandleScoreUpdateRequestTyped), ctx, payload)
}

// HandleScoreUpdateSuccessTyped mocks base method.
func (m *MockHandlers) HandleScoreUpdateSuccessTyped(ctx context.Context, payload *shared.ScoreUpdatedPayloadV1) ([]handlerwrapper.Result, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleScoreUpdateSuccessTyped", ctx, payload)
	ret0, _ := ret[0].([]handlerwrapper.Result)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HandleScoreUpdateSuccessTyped indicates an expected call of HandleScoreUpdateSuccessTyped.
func (mr *MockHandlersMockRecorder) HandleScoreUpdateSuccessTyped(ctx, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleScoreUpdateSuccessTyped", reflect.TypeOf((*MockHandlers)(nil).HandleScoreUpdateSuccessTyped), ctx, payload)
}
