// Code generated by MockGen. DO NOT EDIT.
// Source: ./app/score/watermill/handlers/handlers.go
//
// Generated by this command:
//
//	mockgen -source=./app/score/watermill/handlers/handlers.go -destination=./app/score/mocks/mock_handlers.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	score "github.com/Black-And-White-Club/frolf-bot-shared/events/discord/score"
	scoreevents "github.com/Black-And-White-Club/frolf-bot-shared/events/score"
	handlerwrapper "github.com/Black-And-White-Club/frolf-bot-shared/utils/handlerwrapper"
	message "github.com/ThreeDotsLabs/watermill/message"
	gomock "go.uber.org/mock/gomock"
)

// MockHandler is a mock of Handler interface.
type MockHandler struct {
	ctrl     *gomock.Controller
	recorder *MockHandlerMockRecorder
	isgomock struct{}
}

// MockHandlerMockRecorder is the mock recorder for MockHandler.
type MockHandlerMockRecorder struct {
	mock *MockHandler
}

// NewMockHandler creates a new mock instance.
func NewMockHandler(ctrl *gomock.Controller) *MockHandler {
	mock := &MockHandler{ctrl: ctrl}
	mock.recorder = &MockHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHandler) EXPECT() *MockHandlerMockRecorder {
	return m.recorder
}

// HandleProcessRoundScoresFailed mocks base method.
func (m *MockHandler) HandleProcessRoundScoresFailed(msg *message.Message) ([]*message.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleProcessRoundScoresFailed", msg)
	ret0, _ := ret[0].([]*message.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HandleProcessRoundScoresFailed indicates an expected call of HandleProcessRoundScoresFailed.
func (mr *MockHandlerMockRecorder) HandleProcessRoundScoresFailed(msg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleProcessRoundScoresFailed", reflect.TypeOf((*MockHandler)(nil).HandleProcessRoundScoresFailed), msg)
}

// HandleScoreUpdateFailure mocks base method.
func (m *MockHandler) HandleScoreUpdateFailure(msg *message.Message) ([]*message.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleScoreUpdateFailure", msg)
	ret0, _ := ret[0].([]*message.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HandleScoreUpdateFailure indicates an expected call of HandleScoreUpdateFailure.
func (mr *MockHandlerMockRecorder) HandleScoreUpdateFailure(msg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleScoreUpdateFailure", reflect.TypeOf((*MockHandler)(nil).HandleScoreUpdateFailure), msg)
}

// HandleScoreUpdateRequest mocks base method.
func (m *MockHandler) HandleScoreUpdateRequest(msg *message.Message) ([]*message.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleScoreUpdateRequest", msg)
	ret0, _ := ret[0].([]*message.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HandleScoreUpdateRequest indicates an expected call of HandleScoreUpdateRequest.
func (mr *MockHandlerMockRecorder) HandleScoreUpdateRequest(msg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleScoreUpdateRequest", reflect.TypeOf((*MockHandler)(nil).HandleScoreUpdateRequest), msg)
}

// HandleScoreUpdateSuccess mocks base method.
func (m *MockHandler) HandleScoreUpdateSuccess(msg *message.Message) ([]*message.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleScoreUpdateSuccess", msg)
	ret0, _ := ret[0].([]*message.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HandleScoreUpdateSuccess indicates an expected call of HandleScoreUpdateSuccess.
func (mr *MockHandlerMockRecorder) HandleScoreUpdateSuccess(msg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleScoreUpdateSuccess", reflect.TypeOf((*MockHandler)(nil).HandleScoreUpdateSuccess), msg)
}

// MockHandlers is a mock of Handlers interface.
type MockHandlers struct {
	ctrl     *gomock.Controller
	recorder *MockHandlersMockRecorder
	isgomock struct{}
}

// MockHandlersMockRecorder is the mock recorder for MockHandlers.
type MockHandlersMockRecorder struct {
	mock *MockHandlers
}

// NewMockHandlers creates a new mock instance.
func NewMockHandlers(ctrl *gomock.Controller) *MockHandlers {
	mock := &MockHandlers{ctrl: ctrl}
	mock.recorder = &MockHandlersMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHandlers) EXPECT() *MockHandlersMockRecorder {
	return m.recorder
}

// HandleScoreUpdateFailureTyped mocks base method.
func (m *MockHandlers) HandleScoreUpdateFailureTyped(ctx context.Context, payload *scoreevents.ScoreUpdateFailedPayloadV1) ([]handlerwrapper.Result, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleScoreUpdateFailureTyped", ctx, payload)
	ret0, _ := ret[0].([]handlerwrapper.Result)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HandleScoreUpdateFailureTyped indicates an expected call of HandleScoreUpdateFailureTyped.
func (mr *MockHandlersMockRecorder) HandleScoreUpdateFailureTyped(ctx, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleScoreUpdateFailureTyped", reflect.TypeOf((*MockHandlers)(nil).HandleScoreUpdateFailureTyped), ctx, payload)
}

// HandleScoreUpdateRequestTyped mocks base method.
func (m *MockHandlers) HandleScoreUpdateRequestTyped(ctx context.Context, payload *score.ScoreUpdateRequestDiscordPayloadV1) ([]handlerwrapper.Result, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleScoreUpdateRequestTyped", ctx, payload)
	ret0, _ := ret[0].([]handlerwrapper.Result)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HandleScoreUpdateRequestTyped indicates an expected call of HandleScoreUpdateRequestTyped.
func (mr *MockHandlersMockRecorder) HandleScoreUpdateRequestTyped(ctx, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleScoreUpdateRequestTyped", reflect.TypeOf((*MockHandlers)(nil).HandleScoreUpdateRequestTyped), ctx, payload)
}

// HandleScoreUpdateSuccessTyped mocks base method.
func (m *MockHandlers) HandleScoreUpdateSuccessTyped(ctx context.Context, payload *scoreevents.ScoreUpdatedPayloadV1) ([]handlerwrapper.Result, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleScoreUpdateSuccessTyped", ctx, payload)
	ret0, _ := ret[0].([]handlerwrapper.Result)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HandleScoreUpdateSuccessTyped indicates an expected call of HandleScoreUpdateSuccessTyped.
func (mr *MockHandlersMockRecorder) HandleScoreUpdateSuccessTyped(ctx, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleScoreUpdateSuccessTyped", reflect.TypeOf((*MockHandlers)(nil).HandleScoreUpdateSuccessTyped), ctx, payload)
}
